export let data: Object[] = [
    {
        "client_name": "Tinhvân CONSULTING",
        "leader_fullname": "NGUYỄN VĂN TÂN",
        "id": 100,
        "code": "TS",
        "project_name": "TIMESHEET",
        "project_leader": 9795,
        "client": 3,
        "remark": "",
        "start_date": "2022/05/26 00:00:00",
        "end_date": "2022/07/30 00:00:00",
        "dev_effort_days": 0,
        "created_date": "2022/06/14 16:50:54",
        "created_by": 1,
        "modified_date": "2022/06/24 09:16:06",
        "modified_by": 1
    },
    {
        "client_name": null,
        "leader_fullname": null,
        "id": 97,
        "code": "NTT_US_22",
        "project_name": "NTT_US_22",
        "project_leader": null,
        "client": null,
        "remark": null,
        "start_date": null,
        "end_date": null,
        "dev_effort_days": null,
        "created_date": "2022/06/07 10:26:52",
        "created_by": 1,
        "modified_date": "2022/06/07 10:26:52",
        "modified_by": 1
    },
    {
        "client_name": null,
        "leader_fullname": null,
        "id": 96,
        "code": "LDC_BH",
        "project_name": "LDC_BH",
        "project_leader": null,
        "client": null,
        "remark": null,
        "start_date": null,
        "end_date": null,
        "dev_effort_days": null,
        "created_date": "2022/06/07 10:26:52",
        "created_by": 1,
        "modified_date": "2022/06/07 10:26:52",
        "modified_by": 1
    },
    {
        "client_name": null,
        "leader_fullname": null,
        "id": 95,
        "code": "Nghỉ lễ",
        "project_name": "Nghỉ lễ",
        "project_leader": null,
        "client": null,
        "remark": null,
        "start_date": null,
        "end_date": null,
        "dev_effort_days": null,
        "created_date": "2022/06/07 10:26:52",
        "created_by": 1,
        "modified_date": "2022/06/07 10:26:52",
        "modified_by": 1
    },
    {
        "client_name": null,
        "leader_fullname": null,
        "id": 94,
        "code": "BVG_21",
        "project_name": "BVG_21",
        "project_leader": null,
        "client": null,
        "remark": null,
        "start_date": null,
        "end_date": null,
        "dev_effort_days": null,
        "created_date": "2022/06/07 10:26:52",
        "created_by": 1,
        "modified_date": "2022/06/07 10:26:52",
        "modified_by": 1
    },
    {
        "client_name": null,
        "leader_fullname": null,
        "id": 93,
        "code": "EASIA_BT_22",
        "project_name": "EASIA_BT_22",
        "project_leader": null,
        "client": null,
        "remark": null,
        "start_date": null,
        "end_date": null,
        "dev_effort_days": null,
        "created_date": "2022/06/07 10:26:52",
        "created_by": 1,
        "modified_date": "2022/06/07 10:26:52",
        "modified_by": 1
    },
    {
        "client_name": null,
        "leader_fullname": null,
        "id": 92,
        "code": "Chuyển đổi số",
        "project_name": "Chuyển đổi số",
        "project_leader": null,
        "client": null,
        "remark": null,
        "start_date": null,
        "end_date": null,
        "dev_effort_days": null,
        "created_date": "2022/06/07 10:26:52",
        "created_by": 1,
        "modified_date": "2022/06/07 10:26:52",
        "modified_by": 1
    },
    {
        "client_name": null,
        "leader_fullname": null,
        "id": 91,
        "code": "Showa_BT_22",
        "project_name": "Showa_BT_22",
        "project_leader": null,
        "client": null,
        "remark": null,
        "start_date": null,
        "end_date": null,
        "dev_effort_days": null,
        "created_date": "2022/06/07 10:26:52",
        "created_by": 1,
        "modified_date": "2022/06/07 10:26:52",
        "modified_by": 1
    },
    {
        "client_name": null,
        "leader_fullname": null,
        "id": 90,
        "code": "MAXPORT_US_22",
        "project_name": "MAXPORT_US_22",
        "project_leader": null,
        "client": null,
        "remark": null,
        "start_date": null,
        "end_date": null,
        "dev_effort_days": null,
        "created_date": "2022/06/07 10:26:52",
        "created_by": 1,
        "modified_date": "2022/06/07 10:26:52",
        "modified_by": 1
    },
    {
        "client_name": null,
        "leader_fullname": null,
        "id": 89,
        "code": "HCNS",
        "project_name": "HCNS",
        "project_leader": null,
        "client": null,
        "remark": null,
        "start_date": null,
        "end_date": null,
        "dev_effort_days": null,
        "created_date": "2022/06/07 10:26:52",
        "created_by": 1,
        "modified_date": "2022/06/07 10:26:52",
        "modified_by": 1
    }
];